// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: x/pow/types/params.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params for the pow module
type Params struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// existing fields (if any) should be preserved here; add new fields below
	BlockReward   int64 `protobuf:"varint,10,opt,name=block_reward,json=blockReward,proto3" json:"block_reward,omitempty"`
	FounderShare  int64 `protobuf:"varint,11,opt,name=founder_share,json=founderShare,proto3" json:"founder_share,omitempty"`   // percent (1 means 1)
	MinerShare    int64 `protobuf:"varint,12,opt,name=miner_share,json=minerShare,proto3" json:"miner_share,omitempty"`         // percent (99 means 99)
	TxFeeFlat     int64 `protobuf:"varint,13,opt,name=tx_fee_flat,json=txFeeFlat,proto3" json:"tx_fee_flat,omitempty"`          // fixed fee per tx in smallest unit
	TxFeeFounder  int64 `protobuf:"varint,14,opt,name=tx_fee_founder,json=txFeeFounder,proto3" json:"tx_fee_founder,omitempty"` // percent (10 means 10)
	TxFeeMiner    int64 `protobuf:"varint,15,opt,name=tx_fee_miner,json=txFeeMiner,proto3" json:"tx_fee_miner,omitempty"`       // percent (90 means 90)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_x_pow_types_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_x_pow_types_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_x_pow_types_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetBlockReward() int64 {
	if x != nil {
		return x.BlockReward
	}
	return 0
}

func (x *Params) GetFounderShare() int64 {
	if x != nil {
		return x.FounderShare
	}
	return 0
}

func (x *Params) GetMinerShare() int64 {
	if x != nil {
		return x.MinerShare
	}
	return 0
}

func (x *Params) GetTxFeeFlat() int64 {
	if x != nil {
		return x.TxFeeFlat
	}
	return 0
}

func (x *Params) GetTxFeeFounder() int64 {
	if x != nil {
		return x.TxFeeFounder
	}
	return 0
}

func (x *Params) GetTxFeeMiner() int64 {
	if x != nil {
		return x.TxFeeMiner
	}
	return 0
}

var File_x_pow_types_params_proto protoreflect.FileDescriptor

const file_x_pow_types_params_proto_rawDesc = "" +
	"\n" +
	"\x18x/pow/types/params.proto\x12\x05x.pow\"\xd9\x01\n" +
	"\x06Params\x12!\n" +
	"\fblock_reward\x18\n" +
	" \x01(\x03R\vblockReward\x12#\n" +
	"\rfounder_share\x18\v \x01(\x03R\ffounderShare\x12\x1f\n" +
	"\vminer_share\x18\f \x01(\x03R\n" +
	"minerShare\x12\x1e\n" +
	"\vtx_fee_flat\x18\r \x01(\x03R\ttxFeeFlat\x12$\n" +
	"\x0etx_fee_founder\x18\x0e \x01(\x03R\ftxFeeFounder\x12 \n" +
	"\ftx_fee_miner\x18\x0f \x01(\x03R\n" +
	"txFeeMinerB1Z/github.com/surajdatir/ibtcore/x/pow/types;typesb\x06proto3"

var (
	file_x_pow_types_params_proto_rawDescOnce sync.Once
	file_x_pow_types_params_proto_rawDescData []byte
)

func file_x_pow_types_params_proto_rawDescGZIP() []byte {
	file_x_pow_types_params_proto_rawDescOnce.Do(func() {
		file_x_pow_types_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_x_pow_types_params_proto_rawDesc), len(file_x_pow_types_params_proto_rawDesc)))
	})
	return file_x_pow_types_params_proto_rawDescData
}

var file_x_pow_types_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_x_pow_types_params_proto_goTypes = []any{
	(*Params)(nil), // 0: x.pow.Params
}
var file_x_pow_types_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_x_pow_types_params_proto_init() }
func file_x_pow_types_params_proto_init() {
	if File_x_pow_types_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_x_pow_types_params_proto_rawDesc), len(file_x_pow_types_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_x_pow_types_params_proto_goTypes,
		DependencyIndexes: file_x_pow_types_params_proto_depIdxs,
		MessageInfos:      file_x_pow_types_params_proto_msgTypes,
	}.Build()
	File_x_pow_types_params_proto = out.File
	file_x_pow_types_params_proto_goTypes = nil
	file_x_pow_types_params_proto_depIdxs = nil
}
