// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: pow/tx.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgSubmitAggregate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Miner         string `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	ShareCount    uint64 `protobuf:"varint,2,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	AggregateHash string `protobuf:"bytes,3,opt,name=aggregate_hash,json=aggregateHash,proto3" json:"aggregate_hash,omitempty"`
}

func (x *MsgSubmitAggregate) Reset() {
	*x = MsgSubmitAggregate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pow_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSubmitAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitAggregate) ProtoMessage() {}

func (x *MsgSubmitAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_pow_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitAggregate.ProtoReflect.Descriptor instead.
func (*MsgSubmitAggregate) Descriptor() ([]byte, []int) {
	return file_pow_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSubmitAggregate) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

func (x *MsgSubmitAggregate) GetShareCount() uint64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *MsgSubmitAggregate) GetAggregateHash() string {
	if x != nil {
		return x.AggregateHash
	}
	return ""
}

var File_pow_tx_proto protoreflect.FileDescriptor

var file_pow_tx_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x77, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x70, 0x6f, 0x77, 0x22, 0x72, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x72, 0x61, 0x6a, 0x64, 0x61, 0x74, 0x69, 0x72,
	0x2f, 0x69, 0x62, 0x74, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x78, 0x2f, 0x70, 0x6f, 0x77, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pow_tx_proto_rawDescOnce sync.Once
	file_pow_tx_proto_rawDescData = file_pow_tx_proto_rawDesc
)

func file_pow_tx_proto_rawDescGZIP() []byte {
	file_pow_tx_proto_rawDescOnce.Do(func() {
		file_pow_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_pow_tx_proto_rawDescData)
	})
	return file_pow_tx_proto_rawDescData
}

var file_pow_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pow_tx_proto_goTypes = []interface{}{
	(*MsgSubmitAggregate)(nil), // 0: pow.MsgSubmitAggregate
}
var file_pow_tx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pow_tx_proto_init() }
func file_pow_tx_proto_init() {
	if File_pow_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pow_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSubmitAggregate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pow_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pow_tx_proto_goTypes,
		DependencyIndexes: file_pow_tx_proto_depIdxs,
		MessageInfos:      file_pow_tx_proto_msgTypes,
	}.Build()
	File_pow_tx_proto = out.File
	file_pow_tx_proto_rawDesc = nil
	file_pow_tx_proto_goTypes = nil
	file_pow_tx_proto_depIdxs = nil
}
